#!/bin/sh -e

fips=${ENABLE_FIPS:-false}

cmd=$1
shift
case "$cmd" in
  get-version)
    head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list)
      echo "out autom4te.cache"
    ;;
  prepare-dist)
    ;;
  bootstrap)
    ./autogen.sh

    ;;
  configure)
        if $fips; then
            ./configure --disable-docs --without-oracle \
                --with-dbi --with-dbi-incdir='${prefix}/include/' --with-dbi-libdir='${prefix}/lib/' \
                --without-freetds --without-mysql --without-pgsql \
                --without-sqlite3 --without-sqlite $1
        else
            ./configure --disable-docs --without-oracle \
                --with-dbi --with-dbi-incdir='${prefix}/include/' --with-dbi-libdir='${prefix}/lib/' \
                --with-freetds --with-mysql --with-pgsql \
                --with-sqlite3 --without-sqlite $@
        fi
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
