name: libdbi-drivers
builder:
  name: BalabitBuilder
  configure_options: >
   --with-dbi-libdir=\${prefix}/lib --with-dbi-incdir=\${prefix}/include --disable-docs
   --with-freetds --with-freetds-incdir=\${prefix}/include/ --with-freetds-libdir=\${prefix}/lib/
   --with-mysql --enable-mysql-threadsafe --with-mysql-libdir=\${prefix}/lib/mysql --with-mysql-incdir=\${prefix}/include/mysql
   --with-pgsql --with-pgsql-libdir=\${prefix}/lib --with-pgsql-incdir=\${prefix}/include
   --with-sqlite3 --with-sqlite3-libdir=\${prefix}/lib --with-sqlite3-incdir=\${prefix}/include
   --with-oracle --with-oracle-libdir=\${prefix}/lib --with-oracle-incdir=\${prefix}/include
  flags: "no-make-dist"
platforms:
  - aix-6.1/powerpc
  - linux-glibc2.11/amd64
